apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fiaxke8wq-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:635337c8a46fac5ded520cd43d557ee4171165f0@sha256:d1cc62df6d0f9e526bdcf23e40da70d659c332115f1ce9a14d8efd900d846a58
          name: container-image
