apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fiaxke8wq-java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fiaxke8wq-java-springboot 
  name: fiaxke8wq-java-springboot
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fiaxke8wq-java-springboot 
